### ISSUE TITLE
Replace wget with Invoke-WebRequest for absolute compatibility

### ISSUE THREAD

**Issue by variab1e** [cmarcusreid/git-status-cache-posh-client#10]
Not a major issue I'm sure for many, but I am running a lot of different shells on my system and am actually using msys2 wget alias'd so the install script errors. I replaced the `wget` calls with `Invoke-WebRequest`in `GitStatusCachePoshClient.ps1` and all was well after that.

A quick fix that only ensures compatibility with everything (that is not using aliases)

Thanks for the work!

**Comment by cmarcusreid** [comment]
Good feedback! Thanks!
