### ISSUE TITLE
Auto-Download GitStatusCache.exe

### ISSUE THREAD

**Issue by dahlbyk** [cmarcusreid/git-status-cache-posh-client#4]
A [Chocolatey package](https://github.com/cmarcusreid/git-status-cache-posh-client/issues/3) largely makes this moot, but a potentially quicker intermediate step would be to simplify downloading `GitStatusCache.exe` from https://github.com/cmarcusreid/git-status-cache/releases/latest (https://developer.github.com/v3/repos/releases/#get-the-latest-release).

If `Start-GitStatusCache` notices the expected `exe` isn't found, I propose either:

1. Automatically download latest, or
2. Write a warning along the lines of "Could not find GitStatusCache.exe; call Get-GitStatusCacheExecutable to download."

If downloading latest also captured the release version, you could check for updates as well.

**Comment by dahlbyk** [comment]
As you [pointed out](https://github.com/dahlbyk/posh-git/pull/208#issuecomment-134471670), `install.ps1` already handles downloading so....let's call this an enhancement request to avoid hard-coding v1.0.0? :blush:

**Comment by cmarcusreid** [comment]
I like it. The error message sucks if you didn't come in through an expected route.

**Comment by cmarcusreid** [comment]
Published https://github.com/cmarcusreid/git-status-cache-posh-client/pull/5 for this feedback. I will leave open for a couple of days before merging in case there's feedback.

**Comment by cmarcusreid** [comment]
Merged 768460c9fb3e1d426d9aa1626f729e82a88c0b0f.
