### ISSUE TITLE
Make sure ConvertFrom-Json is available before calling.

### ISSUE THREAD

**Issue by cmarcusreid** [cmarcusreid/git-status-cache-posh-client#6]
All environments may not have Microsoft.Powershell.Utility imported.

**Comment by cmarcusreid** [comment]
Resolved by cb0b3bfbbf941dcac09b0d5189ce11e1797ffc3c.

**Comment by dahlbyk** [comment]
You might also populate `RequiredModules` on your manifest, which in PowerShell 3+ should auto-load the module.
